FROM openjdk:8-jre-alpine
EXPOSE	8761
ADD /build/libs/EurekaDiscoveryServer-0.0.1-SNAPSHOT.jar EurekaDiscoveryServer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","EurekaDiscoveryServer-0.0.1-SNAPSHOT.jar"]